# Generated by Django 4.2.6 on 2023-11-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
